color.rgb = mix(mix(vec3(GetLuminance(color.rgb)), vec3(0.0), 0.65), color.rgb, animation);
beginTextM(8, vec2(6, 10));
    text.fgCol = vec4(1.0, 0.0, 0.0, 1.0);
    printString((_M, _o, _d, _space, _C, _o, _n, _f, _l, _i, _c, _t, _s, _space, _D, _e, _t, _e, _c, _t, _e, _d));
    printLine();
    textColor = color.rgb;
endText(textColor);
color.rgb = mix(textColor, color.rgb, animation);
beginTextM(4, vec2(15, 36));
    printString((_W, _o, _r, _l, _d, _space, _S, _p, _a, _c, _e, _space, _P, _l, _a, _y, _e, _r, _space, _R, _e, _f, _l, _e, _c, _t, _i, _o, _n, _s, _space, _d, _o, _space, _n, _o, _t, _space, _w, _o, _r, _k));
    printLine();
    printString((_c, _o, _r, _r, _e, _c, _t, _l, _y, _space, _w, _i, _t, _h, _space, _t, _h, _e, _space, _3, _D, _space, _S, _k, _i, _n, _space, _L, _a, _y, _e, _r, _s, _space, _M, _o, _d, _dot));
    printLine();
    printLine();
    printString((_E, _i, _t, _h, _e, _r, _space, _d, _i, _s, _a, _b, _l, _e, _space, _W, _o, _r, _l, _d, _space, _S, _p, _a, _c, _e, _space, _P, _l, _a, _y, _e, _r, _space, _R, _e, _f, _l, _e, _c, _t, _i, _o, _n, _s));
    printLine();
    printString((_o, _r, _space, _r, _e, _m, _o, _v, _e, _space, _t, _h, _e, _space, _3, _D, _space, _S, _k, _i, _n, _space, _L, _a, _y, _e, _r, _s, _space, _M, _o, _d, _space, _t, _o, _space, _f, _i, _x, _space, _t, _h, _i, _s, _space, _i, _s, _s, _u, _e, _dot));
    printLine();
endText(textColor);
color.rgb = mix(textColor, color.rgb, animation);
beginTextM(2, vec2(30, 147));
    printString((_D, _i, _s, _a, _b, _l, _e, _space, _W, _o, _r, _l, _d, _space, _S, _p, _a, _c, _e, _space, _P, _l, _a, _y, _e, _r, _space, _R, _e, _f, _l, _e, _c, _t, _i, _o, _n, _s, _space, _u, _n, _d, _e, _r, _colon));
    printLine();
    printString((_O, _t, _h, _e, _r, _space, _gt, _space, _A, _C, _T, _space, _E, _x, _c, _l, _u, _s, _i, _v, _e, _space, _F, _e, _a, _t, _u, _r, _e, _s, _space, _gt, _space, _W, _o, _r, _l, _d, _space, _S, _p, _a, _c, _e, _space, _P, _l, _a, _y, _e, _r, _space, _R, _e, _f, _l, _e, _c, _t, _i, _o, _n, _s, _space, _gt, _space, _W, _S, _space, _P, _l, _a, _y, _e, _r, _space, _R, _e, _f, _l, _e, _c, _t, _i, _o, _n, _s));
    printLine();
    printLine();
    printString((_M, _o, _v, _e, _space, _t, _o, _space, _d, _i, _s, _c, _a, _r, _d, _space, _t, _h, _e, _space, _e, _r, _r, _o, _r, _space, _m, _e, _s, _s, _a, _g, _e, _dot));
    printLine();
endText(textColor);
color.rgb = mix(textColor, color.rgb, animation);
