name = "TenguVerse"
author = "Wondy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80697ffac2b4e78ee47c5adb1086e24305b634c51f1426f819eed96b3fc06ecc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
