name = "TenguVerse"
author = "Wondy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6468468893bfafdaf8a0bb3d70a980ef04048f05ac68a25332c9f441a6fe9528"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
