name = "TenguVerse"
author = "Wondy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1f82ab7afab48903160b85b3dd0c52bbe6ce2ed84e808a05f59de598b549b52"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
