ServerEvents.recipes(event => {
  event.remove({ id: 'farmersdelight:melon_juice' })
  event.remove({ id: 'cobblemon:master_ball' })
  event.remove({ output: 'cobblemon:master_ball' })
  event.remove({ id: 'cobblemon:cherish_ball' })
  event.remove({ input: '#cobblemon:tier_5_poke_balls' })
  event.remove({ mod: 'cobblemon_utility' })
  event.remove({ output: 'explorerscompass:explorerscompass' })
  event.remove({ output: 'naturescompass:naturescompass' })
  event.remove({ output: 'cobblesafari:safari_teleporter' })
  event.remove({ output: 'cobblemon:safari_ball' })
  event.remove({ output: 'cobblemore_lib:safari_ball_lid' })
  event.remove({ output: 'create_klinks_n_klangs:safari_ball_stencil' })
  event.remove({ output: 'minecraft:nether_star' })
  event.remove({ output: 'cobblesafari:safari_teleporter' })
  event.remove({ output: 'cobbledgacha:gacha_machine_4' })
  event.remove({ output: 'cobbledgacha:gacha_machine_2' })

  event.remove({ output: /.*backstabbing.*/ })
})
