#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 27 11:05:12 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.3
