# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "simple"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.regions_unexplored]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.immersiveengineering]
				explosive = true
				sawblade = true
				fusilier = true
				skyline_hook = true
				chemthrower_shot = true
				bulwark = true
				commando = true
				railgun_shot = true
				revolver_shot_wolfpack = true
				fluorescent_tube = true
				cart_reinforcedcrate = true
				revolver_shot_flare = true
				cart_woodencrate = true
				revolver_shot_homing = true
				cart_woodenbarrel = true
				revolver_shot = true
				cart_metalbarrel = true

			[light_sources.settings.entities.biomesoplenty]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.cobblefurnies]
				seat = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.aether]
				slider = true
				poison_dart = true
				sun_spirit = true
				zephyr = true
				flying_cow = true
				whirlwind = true
				golden_dart = true
				poison_needle = true
				floating_block = true
				skyroot_boat = true
				mimic = true
				thunder_crystal = true
				sentry = true
				valkyrie_queen = true
				zephyr_snowball = true
				cockatrice = true
				hammer_projectile = true
				golden_swet = true
				skyroot_chest_boat = true
				fire_crystal = true
				fire_minion = true
				evil_whirlwind = true
				golden_parachute = true
				blue_swet = true
				cloud_minion = true
				valkyrie = true
				phyg = true
				aerbunny = true
				lightning_knife = true
				aerwhale = true
				cold_parachute = true
				enchanted_dart = true
				ice_crystal = true
				sheepuff = true
				aechor_plant = true
				moa = true
				cloud_crystal = true
				tnt_present = true

			[light_sources.settings.entities.rctmod]
				trainer_association = true
				trainer = true

			[light_sources.settings.entities.biomeswevegone]
				pumpkin_warden = true
				oddion = true
				man_o_war = true
				chest_boat = true
				wreath = true
				boat = true

			[light_sources.settings.entities.pokebike]
				yellow_bike = true
				green_bike = true
				red_bike = true
				blue_bike = true

			[light_sources.settings.entities.cobblemon_battle_tower]
				battle_tower_trainer = true

			[light_sources.settings.entities.luggage]
				luggage = true
				ender_luggage = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				bamboo_hopper = true
				cargo_airship = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				tiny_tnt = true
				bullet = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.mynethersdelight]
				strider_rock = true

			[light_sources.settings.entities.create_sa]
				drill_module = true
				vault_module = true
				flamethrower_pr = true
				brass_cube_r = true
				fan_module = true
				flamethrower_pr_2 = true
				magnet_module = true
				brass_drone = true

			[light_sources.settings.entities.expandeddelight]
				cinnamon_boat = true
				cinnamon_chest_boat = true

			[light_sources.settings.entities.cobblemon]
				empty_pokeball = true
				npc = true
				pokemon = true
				generic_bedrock = true
				chest_boat = true
				poke_bobber = true
				boat = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.betterarcheology]
				bombentity = true

			[light_sources.settings.entities.fightorflight]
				bullet_projectile = true
				tornado = true
				floating_spike_projectile = true
				magic_effect = true
				tracing_bullet = true
				whirlpool = true
				arrow_projectile = true
				spike_projectile = true
				sticky_web = true

			[light_sources.settings.entities.farmingforblockheads]
				merchant = true

			[light_sources.settings.entities.sophisticatedbackpacks]
				everlasting_backpack_item = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				angler_fish = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true
				item_frame = true

			[light_sources.settings.entities.mcwfurnitures]
				chair = true
				couch = true

			[light_sources.settings.entities.refurbished_furniture]
				seat = true

			[light_sources.settings.entities.smallships]
				ground_cannon = true
				galley = true
				brigg = true
				drakkar = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.fireworkcapsules]
				capsule_entity = true

			[light_sources.settings.entities.deep_aether]
				quail_egg = true
				eots_segment = true
				windfly = true
				baby_zephyr = true
				aerglow_fish = true
				chest_boat = true
				boat = true
				quail = true
				gentle_wind = true
				fire_projectile = true
				wind_crystal = true
				eots_controller = true
				storm_arrow = true
				venomite_bubble = true
				venomite = true

			[light_sources.settings.entities.createqol]
				statue = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				plunderer = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				cannonball = true
				falling_urn = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
