#Server Country Flags properties file
#Thu Jan 09 23:57:18 CET 2025
borderColor=(65, 65, 65, 255)
displayCooldownFlag=true
displayUnknownFlag=true
flagBorder=true
flagPosition=behindName
forceEnglish=false
mapButton=true
mapButtonRight=true
reloadOnRefresh=false
resolveRedirects=true
serverBrowserIntegration=true
showDistance=true
showDistrict=false
showHomeOnMap=false
showISP=false
useKm=true
